package org.usfirst.frc.team3482.robot;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static Compressor chassisCompressor1;
	public static DoubleSolenoid armsDoubleSolenoid1;
	public static DoubleSolenoid clampDoubleSolenoid1;
	public static SpeedController armSpeedController1;
	public static SpeedController armSpeedController2;
	public static void init() {
		chassisCompressor1 = new Compressor(0);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		armsDoubleSolenoid1 = new DoubleSolenoid(4, 5);      
        LiveWindow.addActuator("Arms", "Double Solenoid 1", armsDoubleSolenoid1);
        clampDoubleSolenoid1 = new DoubleSolenoid(0, 1);      
        LiveWindow.addActuator("Clamp", "Double Solenoid 1", clampDoubleSolenoid1);
        armSpeedController1 = new Talon(1);
        LiveWindow.addActuator("Arm", "Speed Controller 1", (Talon) armSpeedController1);
        armSpeedController2 = new Talon(0);
        LiveWindow.addActuator("Arm", "Speed Controller 2", (Talon) armSpeedController2);
        System.err.println(armSpeedController1);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    // For example to map the left and right motors, you could define the
    // following variables to use with your drivetrain subsystem.
    // public static int leftMotor = 1;
    // public static int rightMotor = 2;
    
    // If you are using multiple modules, make sure to define both the port
    // number and the module. For example you with a rangefinder:
    // public static int rangefinderPort = 1;
    // public static int rangefinderModule = 1;
}
